# ─────────────────────────────────────────────
#  PRODUCTION profile — PostgreSQL
#  Run with: java -jar app.jar --spring.profiles.active=postgres
# ─────────────────────────────────────────────

spring.datasource.url=jdbc:postgresql://localhost:5432/telematicsdb
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false
